name: Deploy Docker Beanstalk Workflow
run-name: Deploy Docker Beanstalk Workflow
on: [workflow_call]

jobs:
  beanstalk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set application name
        id: set-app-name
        run: |
          OWNER_AND_REPO=${{ github.repository }}
          REPO_NAME=$(echo "$OWNER_AND_REPO" | cut -d'/' -f2)
          echo "APP_NAME=${REPO_NAME}" >> $GITHUB_OUTPUT

      - name: Create Dockerrun.aws.json file
        run: |
          echo '{"AWSEBDockerrunVersion": "1", "Image": {"Name": "pedro6571/${{ steps.set-app-name.outputs.APP_NAME }}:latest", "Update": "true"}, "Ports": [{"ContainerPort": 8080, "HostPort": 80}]}' > Dockerrun.aws.json

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: ${{ vars.AWS_REGION }}
          application_name: ${{ steps.set-app-name.outputs.APP_NAME }}
          environment_name: ${{ steps.set-app-name.outputs.APP_NAME }}-${{ github.ref_name }}
          version_label: ${{ github.ref_name }}-${{ github.sha }}
          deployment_package: Dockerrun.aws.json
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
          wait_for_deployment: true
